# Generated by Django 5.2.17 on 2026-09-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='choreoccurrence',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='choreoccurrence',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
